ARG BASE_IMAGE=ubuntu/jre:17_edge
ARG MAVEN_IMAGE=debian:bookworm
FROM $MAVEN_IMAGE as builder

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
        maven \
        binutils \
        openjdk-17-jdk \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

FROM $BASE_IMAGE

COPY --from=builder /bin/sh /bin/sh
COPY --from=builder /usr/bin/chmod /usr/bin/chmod
COPY --from=builder /usr/bin/uname /usr/bin/uname
COPY --from=builder /usr/bin/dirname /usr/bin/dirname
# note, Temurin base does not install into /etc/maven and /usr/share/java
# other base might require copying those folders
COPY --from=builder /usr/share/maven /usr/share/maven
COPY --from=builder /usr/share/java /usr/share/java
COPY --from=builder /etc/maven /etc/maven

ENV JAVA_HOME=/opt/java

# Add javac compiler for maven (it always recompiles package-info.java)
COPY --from=builder /usr/lib/jvm/default-java/bin/javac \
    /opt/java/bin/
# compatibility signatures
COPY --from=builder /usr/lib/jvm/default-java/lib/ct.sym \
    /opt/java/lib/
# additional jars

# copy modules
COPY --from=builder /usr/lib/jvm/default-java/lib/modules \
    /opt/java/lib/

ENTRYPOINT [ "/usr/share/maven/bin/mvn" ]
