ARG BUILD_IMAGE=debian:bookworm
ARG USER=app
ARG UID=101
ARG GROUP=app
ARG GID=101

FROM ${BUILD_IMAGE}
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
        maven \
        binutils \
        openjdk-17-jdk \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

ARG USER
ARG UID
ARG GROUP
ARG GID

RUN install -d -m 0755 -o $UID -g $GID /home/$USER \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/etc/passwd

USER $UID:$GID
